"""Paper-ready channel-selection tables from the frozen artifacts.

Reads channel_ranking.json, budgets.json and stability.json (all committed,
provenance-stamped) and writes paper/channel_tables.md. Nothing is recomputed
from EEG; every number here is already in a frozen file, so the tables cannot
drift from what the sweep trained on.

Usage: python scripts/channel_tables.py [--out paper/channel_tables.md]
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.channels import SENSORIMOTOR_POOL, load_budgets, load_ranking
from src.utils import ARTIFACTS_DIR, REPO_ROOT

def hemisphere(ch):
    """10-20 convention: odd trailing digit = left, even = right, z = midline."""
    if ch.endswith("z"):
        return "midline"
    digits = "".join(c for c in ch if c.isdigit())
    if not digits:
        return "?"
    return "left" if int(digits[-1]) % 2 else "right"


def md_table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(REPO_ROOT / "paper" / "channel_tables.md"))
    args = ap.parse_args()

    ranked, rank_prov = load_ranking()
    ranking_json = json.load(open(ARTIFACTS_DIR / "channel_ranking.json"))
    scores = dict(zip(ranking_json["channels"], ranking_json["scores"]))
    budgets = load_budgets()
    stab = json.load(open(ARTIFACTS_DIR / "stability.json"))
    boot = stab["bootstrap_topk_frequency"]
    per_subj = stab["per_subject"]
    pool = set(SENSORIMOTOR_POOL)
    rank_of = {c: i + 1 for i, c in enumerate(ranked)}

    sections = []
    sections.append(
        "# Channel-selection tables\n\n"
        "Generated by `scripts/channel_tables.py` from the frozen artifacts. "
        "Ranking: {} over {}–{} Hz, {} training subjects "
        "(commit {}, config {}). Stability: {} bootstrap resamples of the training subjects, seed {}.\n".format(
            ranking_json["method"], ranking_json["band_hz"][0], ranking_json["band_hz"][1],
            ranking_json["n_train_subjects"], rank_prov["git_commit"][:7], rank_prov["config_hash"],
            stab["n_bootstrap"], stab["seed"],
        )
    )

    # ---- Table 1: ranking (top 16 + canonical motor electrodes)
    show = list(ranked[:16])
    for c in ("C3", "Cz", "CP3", "C1"):
        if c not in show:
            show.append(c)
    rows = []
    for c in show:
        rows.append((rank_of[c], c, "{:.4f}".format(scores[c]), hemisphere(c),
                     "yes" if c in pool else "no"))
    rows.sort()
    sections.append("## Table 1. Electrode ranking (top 16, plus canonical motor sites)\n\n" +
                    md_table(["Rank", "Electrode", "Fisher score", "Hemisphere", "In sensorimotor pool"], rows))

    # ---- Table 2: frozen channel set per budget with bootstrap frequency
    rows = []
    for k_str, entry in sorted(budgets["sets"].items(), key=lambda kv: int(kv[0])):
        k = int(k_str)
        if k >= 64:
            continue
        chans = entry["ranking_order"]
        freq = boot.get(k_str, {})
        cells = ", ".join("{} ({:.2f})".format(c, freq.get(c, float("nan"))) for c in chans)
        n_left = sum(hemisphere(c) == "left" for c in chans)
        n_right = sum(hemisphere(c) == "right" for c in chans)
        n_pool = sum(c in pool for c in chans)
        rows.append((k, cells, "{}/{}".format(n_left, n_right), "{}/{}".format(n_pool, k)))
    sections.append(
        "## Table 2. Frozen selected-channel set per budget\n\n"
        "Electrodes in ranking order; parentheses give the fraction of bootstrap resamples in which "
        "that electrode was in the top-k.\n\n" +
        md_table(["k", "Selected electrodes (bootstrap top-k frequency)", "Left/right", "In sensorimotor pool"], rows)
    )

    # ---- Table 3: most frequently selected electrodes under bootstrap, per budget
    rows = []
    for k_str in sorted(boot, key=int):
        top = sorted(boot[k_str].items(), key=lambda kv: -kv[1])[:8]
        rows.append((int(k_str), ", ".join("{} ({:.2f})".format(c, f) for c, f in top)))
    sections.append("## Table 3. Channel-frequency summary (bootstrap over training subjects)\n\n"
                    "Eight most frequently selected electrodes at each budget.\n\n" +
                    md_table(["k", "Electrode (frequency)"], rows))

    # ---- Table 4: subject-specific vs shared montage
    rows = []
    for k_str in sorted(per_subj, key=int):
        ov = per_subj[k_str]["overlap"]
        per = ov["per_subject"]
        n = len(per)
        zero = sum(1 for v in per if v == 0)
        half = sum(1 for v in per if v >= 0.5)
        top = sorted(per_subj[k_str]["frequency"].items(), key=lambda kv: -kv[1])[:5]
        rows.append((
            int(k_str),
            "{:.2f} ± {:.2f}".format(ov["mean"], ov["std"]),
            "{}/{}".format(zero, n),
            "{}/{}".format(half, n),
            ", ".join("{} ({:.2f})".format(c, f) for c, f in top),
        ))
    sections.append(
        "## Table 4. Subject-specific versus shared montage\n\n"
        "Each training subject was ranked alone; overlap is |personal top-k ∩ shared top-k| / k. "
        "Frequency is the fraction of subjects whose personal top-k contained the electrode.\n\n" +
        md_table(["k", "Overlap mean ± SD", "Subjects with zero overlap", "Subjects with overlap ≥ 0.5",
                  "Most-selected electrodes in personal rankings"], rows) +
        "\n\nCaveat: personal rankings rest on ≤45 trials per subject and are noisy; "
        "this table supports a qualitative claim (shared and personal selections diverge), not a per-subject recommendation."
    )

    # ---- interpretation, written from the frozen numbers above
    k4 = budgets["sets"]["4"]["ranking_order"]
    ov4 = per_subj["4"]["overlap"]
    sections.append(
        "## Notes for the write-up\n\n"
        "- The univariate Fisher ranking selects spatially adjacent right-hemisphere electrodes: the frozen k=4 set is "
        "{} with no left-hemisphere member, and C3 (the canonical left motor site) does not enter until rank {}. "
        "Neighbouring electrodes re-measure the same cortical sources through volume conduction, so a top-k of a "
        "univariate score is redundant by construction; this is a limitation of the selection method, not of the montage.\n"
        "- Under bootstrap resampling of training subjects only C4 is stable at small budgets ({:.2f} at k=4); "
        "CP4, C6 and CP6 are selected in roughly half of resamples and are interchangeable with F7, PO7 and AF7.\n"
        "- Frontal and occipital sites (F7, AF7, PO7, O1) outrank most of the sensorimotor strip. These are plausible "
        "gaze- or attention-related correlates of the cue rather than motor ERD; the sensorimotor-restricted arm of the "
        "sweep exists to test that.\n"
        "- Personal rankings barely overlap the shared one at small k (mean overlap {:.2f} at k=4; {} of {} subjects share "
        "no electrode with the shared top-4) and personal top picks are dominated by occipital/frontal sites. "
        "With ≤45 trials per subject this is a qualitative observation, not evidence for personalised montages.\n"
        "- Numbers in this file are selection statistics only. Decoding performance per budget comes from the sweep "
        "results and must be cited from provenance-stamped rows.".format(
            ", ".join(k4), rank_of["C3"], boot["4"]["C4"], ov4["mean"],
            sum(1 for v in ov4["per_subject"] if v == 0), len(ov4["per_subject"]))
    )

    text = "\n\n".join(sections) + "\n"
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(text)
    print("-> wrote", out)


if __name__ == "__main__":
    main()
